sudo: false
language: python
cache: pip
python:
  - "3.8"
  - "3.9"
  - "3.10"
notifications:
  email: false
# command to install dependencies
install:
  - "pip install --upgrade pip setuptools wheel pytest importlib-metadata"
  - "pip install -r requirements.txt"  
  - "pip install ."
# command to run nosetests
script: pytest